import type { SchemaDefinition, ColumnDefinition } from '../schema/types.js';

/**
 * Generates a TypeScript `Database` interface from a SchemaDefinition.
 */
export class TypeGenerator {
    generate(schema: SchemaDefinition): string {
        const lines: string[] = [];

        lines.push('// Auto-generated by kysely-schema — DO NOT EDIT');
        lines.push('');
        lines.push('import type { Generated, ColumnType } from \'kysely\';');
        lines.push('');

        // Generate individual table interfaces
        for (const [tableName, tableDef] of Object.entries(schema.tables)) {
            const pascalName = this.toPascalCase(tableName);
            lines.push(`export interface ${pascalName}Table {`);

            for (const [colName, colDef] of Object.entries(tableDef.columns)) {
                const tsType = this.mapToTypeScript(colDef);
                lines.push(`  ${colName}: ${tsType};`);
            }

            lines.push('}');
            lines.push('');
        }

        // Generate the Database interface
        lines.push('export interface Database {');
        for (const tableName of Object.keys(schema.tables)) {
            const pascalName = this.toPascalCase(tableName);
            lines.push(`  ${tableName}: ${pascalName}Table;`);
        }
        lines.push('}');
        lines.push('');

        return lines.join('\n');
    }

    // ── Private helpers ──────────────────────────────────────────────────

    private mapToTypeScript(def: ColumnDefinition): string {
        const baseType = this.baseTypeMap(def.type);
        let tsType = baseType;

        // serial / auto-increment columns are Generated<>
        if (def.type === 'serial') {
            tsType = `Generated<${baseType}>`;
        }

        // Columns with a default value but not serial are also Generated<>
        if (def.default !== undefined && def.type !== 'serial') {
            tsType = `Generated<${baseType}>`;
        }

        // Nullable
        if (def.nullable || (!def.notNull && !def.primaryKey && def.type !== 'serial')) {
            tsType += ' | null';
        }

        return tsType;
    }

    private baseTypeMap(type: string): string {
        const map: Record<string, string> = {
            serial: 'number',
            integer: 'number',
            bigint: 'string',
            decimal: 'string',
            text: 'string',
            varchar: 'string',
            timestamp: 'Date',
            date: 'Date',
            time: 'string',
            boolean: 'boolean',
            json: 'unknown',
            jsonb: 'unknown',
            binary: 'Buffer',
            uuid: 'string',
        };
        return map[type] || 'unknown';
    }

    private toPascalCase(str: string): string {
        return str
            .split(/[_\- ]+/)
            .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
            .join('');
    }
}
